import matplotlib.pyplot as mpl
import numpy as np

# 1
x = np.linspace(-2, 2, 100)
f6 = (1/(4*6))*(x**2)
f2 = (1/(4*2))*(x**2)
mpl.plot(x, f2, 'r' , label = 'f=2', linewidth='2')
mpl.plot(x, f6, 'b' , label = 'f=6', linewidth='6')
mpl.legend()
mpl.title("Parabola plots with varying focal length")
mpl.xlabel("x")
mpl.ylabel("y")
mpl.show()
mpl.close()
# 2
x = np.linspace(-4, 4, 25)
y = (2*x**3)+(3*x**2)-(11*x)-(6)
mpl.plot(x, y, 'y*')
mpl.title("Plot of cubic polynomial")
mpl.xlabel("x values")
mpl.ylabel("y values")
mpl.show()
# 3
mpl.close()
fig, axs = mpl.subplots(2)
fig.suptitle('Plot of cos(x) and sin(x)')
x = np.linspace(-2*np.pi, 2*np.pi, 100)
cos = np.cos(x)
sin = np.sin(x)
axs[0].plot(x, cos,'r', label='cos(x)')
axs[0].set_xlabel("x")
axs[0].set_ylabel("y=cos(x)")
axs[0].legend(loc='lower right')
axs[0].set_yticks(np.linspace(-1,1, 3))
axs[0].grid()
axs[1].plot(x, sin,'b', label='sin(x)')
axs[1].set_xlabel("x")
axs[1].set_ylabel("y=sin(x)")
axs[1].legend(loc='upper right')
axs[1].set_yticks(np.linspace(-1,1, 3))
axs[1].grid()
fig.show()